const StyleDictionary = require("style-dictionary");
const hslTransform = require("./transforms/hsl");

// ── Register custom transform ─────────────────────────────────────────────
StyleDictionary.registerTransform(hslTransform);

StyleDictionary.registerTransformGroup({
  name: "smartvault/css",
  transforms: ["attribute/cti", "name/cti/kebab", "color/hsl-channels"],
});

// ── Custom formatter: CSS variables grouped by :root and .dark ───────────
StyleDictionary.registerFormat({
  name: "smartvault/css-variables",
  formatter({ dictionary, options }) {
    const { selector = ":root" } = options;
    const vars = dictionary.allTokens
      .map((t) => `  --${t.name}: ${t.value};`)
      .join("\n");
    return `${selector} {\n${vars}\n}\n`;
  },
});

// ── Custom formatter: Tailwind theme extension JS ─────────────────────────
StyleDictionary.registerFormat({
  name: "smartvault/tailwind-theme",
  formatter({ dictionary }) {
    const colors = {};
    const spacing = {};
    const fontSize = {};
    const borderRadius = {};

    dictionary.allTokens.forEach((t) => {
      const [category, ...rest] = t.path;
      const key = rest.join("-") || t.name;

      if (category === "color") {
        colors[key] = `hsl(var(--${t.name}))`;
      } else if (category === "spacing") {
        spacing[key] = `var(--${t.name})`;
      } else if (category === "font" && rest[0] === "size") {
        fontSize[rest.slice(1).join("-")] = `var(--${t.name})`;
      } else if (category === "border" && rest[0] === "radius") {
        borderRadius[rest.slice(1).join("-")] = `var(--${t.name})`;
      }
    });

    return [
      "/** Auto-generated by SmartVault token sync — do not edit manually */",
      "module.exports = {",
      `  colors: ${JSON.stringify(colors, null, 4)},`,
      `  spacing: ${JSON.stringify(spacing, null, 4)},`,
      `  fontSize: ${JSON.stringify(fontSize, null, 4)},`,
      `  borderRadius: ${JSON.stringify(borderRadius, null, 4)},`,
      "};",
    ].join("\n");
  },
});

// ── Build configs ─────────────────────────────────────────────────────────
const TOKENS_DIR = "../../tokens";
const OUT_DIR = "../../frontend/src/styles";

const lightConfig = {
  source: [`${TOKENS_DIR}/global.json`, `${TOKENS_DIR}/light.json`],
  platforms: {
    css: {
      transformGroup: "smartvault/css",
      buildPath: `${OUT_DIR}/`,
      files: [
        {
          destination: "tokens.light.css",
          format: "smartvault/css-variables",
          options: { selector: ":root" },
        },
      ],
    },
  },
};

const darkConfig = {
  source: [`${TOKENS_DIR}/global.json`, `${TOKENS_DIR}/dark.json`],
  platforms: {
    css: {
      transformGroup: "smartvault/css",
      buildPath: `${OUT_DIR}/`,
      files: [
        {
          destination: "tokens.dark.css",
          format: "smartvault/css-variables",
          options: { selector: ".dark" },
        },
      ],
    },
  },
};

const tailwindConfig = {
  source: [`${TOKENS_DIR}/global.json`, `${TOKENS_DIR}/light.json`],
  platforms: {
    js: {
      transformGroup: "smartvault/css",
      buildPath: `${OUT_DIR}/`,
      files: [
        {
          destination: "tailwind-tokens.js",
          format: "smartvault/tailwind-theme",
        },
      ],
    },
  },
};

[lightConfig, darkConfig, tailwindConfig].forEach((cfg) => {
  const sd = StyleDictionary.extend(cfg);
  sd.buildAllPlatforms();
});

console.log("✅ Tokens built → frontend/src/styles/");
