/** Auto-generated by SmartVault token sync — do not edit manually */
module.exports = {
  colors: {
    "background": "hsl(var(--color-background))",
    "foreground": "hsl(var(--color-foreground))",
    "primary": "hsl(var(--color-primary))",
    "primary-foreground": "hsl(var(--color-primary-foreground))",
    "secondary": "hsl(var(--color-secondary))",
    "secondary-foreground": "hsl(var(--color-secondary-foreground))",
    "muted": "hsl(var(--color-muted))",
    "muted-foreground": "hsl(var(--color-muted-foreground))",
    "accent": "hsl(var(--color-accent))",
    "accent-foreground": "hsl(var(--color-accent-foreground))",
    "destructive": "hsl(var(--color-destructive))",
    "destructive-foreground": "hsl(var(--color-destructive-foreground))",
    "border": "hsl(var(--color-border))",
    "input": "hsl(var(--color-input))",
    "ring": "hsl(var(--color-ring))",
    "card": "hsl(var(--color-card))",
    "card-foreground": "hsl(var(--color-card-foreground))",
    "popover": "hsl(var(--color-popover))",
    "popover-foreground": "hsl(var(--color-popover-foreground))",
    "warning": "hsl(var(--color-warning))",
    "warning-foreground": "hsl(var(--color-warning-foreground))",
    "success": "hsl(var(--color-success))",
    "success-foreground": "hsl(var(--color-success-foreground))"
},
  spacing: {
    "1": "var(--spacing-1)",
    "2": "var(--spacing-2)",
    "3": "var(--spacing-3)",
    "4": "var(--spacing-4)",
    "5": "var(--spacing-5)",
    "6": "var(--spacing-6)",
    "8": "var(--spacing-8)",
    "10": "var(--spacing-10)",
    "12": "var(--spacing-12)",
    "16": "var(--spacing-16)"
},
  fontSize: {
    "xs": "var(--font-size-xs)",
    "sm": "var(--font-size-sm)",
    "base": "var(--font-size-base)",
    "lg": "var(--font-size-lg)",
    "xl": "var(--font-size-xl)",
    "2xl": "var(--font-size-2xl)",
    "3xl": "var(--font-size-3xl)",
    "4xl": "var(--font-size-4xl)"
},
  borderRadius: {
    "sm": "var(--border-radius-sm)",
    "md": "var(--border-radius-md)",
    "lg": "var(--border-radius-lg)",
    "xl": "var(--border-radius-xl)",
    "full": "var(--border-radius-full)"
},
};